; Generated by Pascal x86 compiler
; Build: nasm -f elf32 output.asm -o output.o
;        gcc -m32 -no-pie output.o -o output


section .data
_fmt_int  db "%d", 0
_fmt_nl   db "%d", 10, 0
_fmt_true  db "TRUE", 10, 0
_fmt_false db "FALSE", 10, 0
_fmt_char db "%c", 0
_fmt_scan_int  db "%d", 0
_fmt_scan_char db " %c", 0

section .bss
    _n resd 1
    _result resd 1

section .text
    global main
    extern printf, scanf

    ; --- function fact ---
_func_fact:
    push     ebp
    mov      ebp, esp
    mov      eax, dword [ebp+8]
    push     eax
    mov      eax, 1
    mov      ebx, eax
    pop      eax
    cmp      eax, ebx
    mov      eax, 0
    mov      ecx, 1
    cmovle   eax, ecx
    test     eax, eax
    jz       .else_1
    mov      eax, 1
    mov      esp, ebp
    pop      ebp
    ret
    jmp      .if_end_2
.else_1:
    mov      eax, dword [ebp+8]
    push     eax
    mov      eax, dword [ebp+8]
    push     eax
    mov      eax, 1
    mov      ebx, eax
    pop      eax
    sub      eax, ebx
    push     eax
    call     _func_fact
    add      esp, 4
    mov      ebx, eax
    pop      eax
    imul     eax, ebx
    mov      esp, ebp
    pop      ebp
    ret
.if_end_2:
    mov      esp, ebp
    pop      ebp
    ret

    ; --- main ---
main:
    push     ebp
    mov      ebp, esp
    mov      eax, 6
    mov      dword [_n], eax
    mov      eax, dword [_n]
    push     eax
    call     _func_fact
    add      esp, 4
    push     eax
    push     _fmt_nl
    call     printf
    add      esp, 8
    mov      esp, ebp
    pop      ebp
    xor      eax, eax
    ret

section .note.GNU-stack noalloc noexec nowrite progbits
